In [1]:
import imdb_scraper

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('100_film_directors.csv')

In [4]:
urls = df['IMDb_URI'].to_list()

In [5]:
import re
director_ids = []
for url in urls:
    pattern = r'(nm\d+)/'
# Using re.search to find the pattern in the URL
    match = re.search(pattern, url)
    if match:
        extracted_string = match.group(1)
        director_ids.append(extracted_string)
    else:
        print("Pattern not found in the URL.")

In [6]:
import json
import os
for id in director_ids:
    credits_dictionary = imdb_scraper.get_full_credits_for_director(id)
    directory = id
    if not os.path.exists(directory):
        os.makedirs(directory)
        json_file_path = os.path.join(directory, '{}.json'.format(id))
        with open(json_file_path, 'w') as json_file:
            json.dump(credits_dictionary, json_file)

textutils.py, 136, (<class 'requests.exceptions.ReadTimeout'>, ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='www.imdb.com', port=443): Read timed out. (read timeout=10)")), <traceback object at 0x140e6a8c0>)	uri: https://www.imdb.com/name/nm0000165/fullcredits/
textutils.py, 136, (<class 'KeyboardInterrupt'>, KeyboardInterrupt(), <traceback object at 0x143681300>)	uri: https://www.imdb.com/name/nm1347153/fullcredits/
textutils.py, 136, (<class 'requests.exceptions.ReadTimeout'>, ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='www.imdb.com', port=443): Read timed out. (read timeout=10)")), <traceback object at 0x140919740>)	uri: https://www.imdb.com/name/nm0000229/fullcredits/

In [7]:
import json
import os
def read_json_files_from_directory(directory):
    json_data = []
    for filename in os.listdir(directory):
        if filename.endswith('.json'):
            filepath = os.path.join(directory, filename)
            with open(filepath, 'r') as file:
                data = json.load(file)
                json_data.append(data)
    return json_data

In [11]:
all_json_data = []

# Loop through each directory and read JSON files
all_credits = []
for directory in director_ids:
    try:
        json_data = read_json_files_from_directory(directory)
        all_json_data.extend(json_data)
        for entry in json_data:
            director_name = entry.get("director_name", "")
            credits = entry.get("credits", [])
    
    # Extract credits
        for credit in credits:
            credit["director_name"] = director_name
            credit["director_id"] = directory
            all_credits.append(credit)
    except FileNotFoundError:
        print("Directory not found:", directory)

In [12]:
df_2 = pd.DataFrame(all_credits)

In [18]:
output_csv = 'credits.csv'
df_2.to_csv(output_csv, index=False)

In [13]:
df_2

,title,uri,year,note,director_name,director_id
0,Demimonde,https://www.imdb.com/title/tt7890594/?ref_=nm_...,,(TV Series) (1 episode) (pre-production) - Epi...,J.J. Abrams,nm0009190
1,Duster,https://www.imdb.com/title/tt12160826/?ref_=nm...,,(TV Series) (1 episode) (filming) - Episode #1.1,J.J. Abrams,nm0009190
2,Spyjinx,https://www.imdb.com/title/tt8434496/?ref_=nm_...,2019,(Video Game) (creative director),J.J. Abrams,nm0009190
3,Star Wars: Episode IX - The Rise of Skywalker,https://www.imdb.com/title/tt2527338/?ref_=nm_...,2019,,J.J. Abrams,nm0009190
4,Jimmy Kimmel's the Terrific Ten,https://www.imdb.com/title/tt14279324/?ref_=nm...,2017,(Short),J.J. Abrams,nm0009190
...,...,...,...,...,...,...
2982,Songs My Brothers Taught Me,https://www.imdb.com/title/tt3566788/?ref_=nm_...,2015,,Chloé Zhao,nm2125482
2983,Benachin,https://www.imdb.com/title/tt1630305/?ref_=nm_...,2011,(Short),Chloé Zhao,nm2125482
2984,Daughters,https://www.imdb.com/title/tt1517671/?ref_=nm_...,2010,(Short),Chloé Zhao,nm2125482
2985,The Atlas Mountains,https://www.imdb.com/title/tt1362356/?ref_=nm_...,2009,(Short),Chloé Zhao,nm2125482
2986,Post,https://www.imdb.com/title/tt1522245/?ref_=nm_...,2008,(Short),Chloé Zhao,nm2125482

In [16]:
df_2['title_ids'] = df_2['uri'].str.extract(r'(tt\d+)')

In [21]:
title_ids_list = df_2['title_ids'].to_list()

In [22]:
for title in title_ids_list:
    crew_dictionary = get_full_crew_for_movie

['tt7890594',
 'tt12160826',
 'tt8434496',
 'tt2527338',
 'tt14279324',
 'tt2488496',
 'tt1408101',
 'tt1650062',
 'tt1568769',
 'tt0935087',
 'tt7935372',
 'tt0796366',
 'tt0386676',
 'tt0320037',
 'tt0317919',
 'tt0285333',
 'tt0411008',
 'tt0134247',
 'tt21803526',
 'tt15140278',
 'tt8593904',
 'tt7139936',
 'tt5825380',
 'tt4354616',
 'tt4513674',
 'tt5285062',
 'tt3715320',
 'tt2870756',
 'tt2334873',
 'tt1859650',
 'tt1605783',
 'tt1182350',
 'tt1178663',
 'tt0497465',
 'tt0795493',
 'tt0457513',
 'tt0416320',
 'tt0378947',
 'tt0313792',
 'tt0278823',
 'tt0299150',
 'tt0298810',
 'tt0256524',
 'tt0196216',
 'tt0158371',
 'tt0120533',
 'tt0118954',
 'tt0116242',
 'tt0113819',
 'tt0109644',
 'tt0109348',
 'tt0107507',
 'tt0104466',
 'tt0105378',
 'tt0099012',
 'tt0097123',
 'tt0097965',
 'tt0094663',
 'tt0093940',
 'tt0093818',
 'tt0091167',
 'tt0089853',
 'tt0087003',
 'tt0086637',
 'tt0084329',
 'tt0081554',
 'tt0079522',
 'tt0077742',
 'tt0075686',
 'tt0073312',
 'tt0070707',
 'tt0068555',
 'tt0133962',
 'tt0066808',
 'tt0065063',
 'tt0061177',
 'tt30144839',
 'tt31068813',
 'tt29958259',
 'tt18360798',
 'tt11271038',
 'tt13236304',
 'tt11906292',
 'tt15761196',
 'tt11217908',
 'tt10740192',
 'tt10516984',
 'tt10548804',
 'tt8150928',
 'tt5776858',
 'tt7707022',
 'tt8150920',
 'tt6837160',
 'tt6793564',
 'tt6073548',
 'tt5699478',
 'tt15837268',
 'tt5181568',
 'tt4995590',
 'tt5081994',
 'tt1791528',
 'tt5094720',
 'tt3471822',
 'tt1560747',
 'tt7891984',
 'tt0469494',
 'tt0378338',
 'tt7359992',
 'tt7359888',
 'tt0367553',
 'tt0365082',
 'tt6793526',
 'tt0272338',
 'tt0486767',
 'tt5094674',
 'tt0072562',
 'tt0331625',
 'tt5094514',
 'tt0175880',
 'tt5094696',
 'tt5094408',
 'tt5094378',
 'tt0255171',
 'tt0118749',
 'tt5094676',
 'tt0119256',
 'tt0138363',
 'tt0138403',
 'tt30840798',
 'tt28912885',
 'tt28912858',
 'tt28912758',
 'tt16968450',
 'tt28259927',
 'tt14230388',
 'tt21071898',
 'tt8847712',
 'tt5104604',
 'tt6282412',
 'tt2278388',
 'tt3331512',
 'tt2808968',
 'tt2219564',
 'tt3707014',
 'tt1748122',
 'tt12753124',
 'tt0432283',
 'tt12753128',
 'tt1094249',
 'tt0838221',
 'tt4283584',
 'tt0362270',
 'tt0265666',
 'tt0128445',
 'tt0115734',
 'tt0109322',
 'tt4257262',
 'tt13207736',
 'tt11421266',
 'tt8201814',
 'tt6149182',
 'tt1837492',
 'tt5420376',
 'tt3973820',
 'tt4971144',
 'tt3488298',
 'tt5222904',
 'tt2238050',
 'tt1523483',
 'tt0780608',
 'tt0370986',
 'tt0244842',
 'tt0127296',
 'tt0119809',
 'tt0112887',
 'tt0108366',
 'tt0104745',
 'tt0191250',
 'tt0094134',
 'tt31228510',
 'tt28277817',
 'tt11548822',
 'tt3920596',
 'tt3502262',
 'tt5478730',
 'tt3721936',
 'tt1181614',
 'tt1232776',
 'tt12431444',
 'tt0471030',
 'tt0406404',
 'tt0388534',
 'tt0340078',
 'tt1259773',
 'tt1223169',
 'tt13935992',
 'tt28363850',
 'tt13833688',
 'tt13623992',
 'tt5109784',
 'tt7331874',
 'tt1959490',
 'tt7087922',
 'tt0947798',
 'tt1125849',
 'tt0414993',
 'tt0180093',
 'tt0138704',
 'tt0399670',
 'tt1735215',
 'tt0167352',
 'tt0365809',
 'tt0902284',
 'tt14509130',
 'tt14271498',
 'tt7203552',
 'tt8521876',
 'tt7545266',
 'tt6064882',
 'tt7720790',
 'tt7660850',
 'tt6958014',
 'tt4578474',
 'tt5929750',
 'tt2342652',
 'tt3609352',
 'tt1698641',
 'tt2727156',
 'tt2056366',
 'tt2087571',
 'tt1190689',
 'tt1797404',
 'tt1509004',
 'tt1844624',
 'tt1826940',
 'tt1299365',
 'tt1515193',
 'tt1477837',
 'tt1512746',
 'tt0403702',
 'tt0805669',
 'tt0386676',
 'tt0437825',
 'tt0248654',
 'tt0367313',
 'tt0778658',
 'tt25815200',
 'tt21193946',
 'tt25815192',
 'tt0279113',
 'tt0178165',
 'tt0193676',
 'tt0200530',
 'tt0202752',
 'tt0106028',
 'tt0252644',
 'tt0120197',
 'tt30446847',
 'tt6160448',
 'tt7653254',
 'tt5536736',
 'tt1683048',
 'tt2872462',
 'tt1791682',
 'tt0446672',
 'tt2347569',
 'tt1234654',
 'tt0072562',
 'tt0757361',
 'tt0367089',
 'tt0999874',
 'tt0119291',
 'tt0119717',
 'tt0113537',
 'tt1541155',
 'tt4998632',
 'tt28613516',
 'tt8106534',
 'tt3371366',
 'tt4172430',
 'tt2109248',
 'tt1980209',
 'tt1399103',
 'tt1055369',
 'tt0418279',
 'tt0399201',
 'tt0476288',
 'tt0172156',
 'tt7023212',
 'tt0213149',
 'tt0120591',
 'tt7023196',
 'tt0117500',
 'tt8300958',
 'tt0112442',
 'tt0364980',
 'tt7023176',
 'tt7023152',
 'tt11163684',
 'tt7019730',
 'tt0274831',
 'tt7023110',
 'tt7023138',
 'tt7023126',
 'tt4645580',
 'tt0343746',
 'tt7023096',
 'tt7022950',
 'tt7022980',
 'tt7023034',
 'tt7022958',
 'tt7023066',
 'tt7022998',
 'tt7022694',
 'tt7022520',
 'tt0471307',
 'tt2069880',
 'tt7022916',
 'tt7010286',
 'tt7022780',
 'tt7022406',
 'tt4109058',
 'tt7022760',
 'tt7022728',
 'tt7022788',
 'tt7022656',
 'tt7022898',
 'tt7022518',
 'tt7022614',
 'tt7022426',
 'tt7022420',
 'tt7022400',
 'tt7022448',
 'tt7022510',
 'tt19394520',
 'tt17500324',
 'tt9462672',
 'tt5390504',
 'tt6075918',
 'tt4532536',
 'tt1790885',
 'tt1602129',
 'tt0887912',
 'tt0972390',
 'tt0364823',
 'tt0267626',
 'tt0210382',
 'tt0106028',
 'tt0114558',
 'tt0106175',
 'tt0102685',
 'tt0099160',
 'tt11495402',
 'tt0093605',
 'tt0085872',
 'tt0108087',
 'tt16042972',
 'tt13503300',
 'tt13472328',
 'tt8359476',
 'tt2146170',
 'tt2245013',
 'tt2073510',
 'tt1252330',
 'tt1459232',
 'tt1085469',
 'tt0486531',
 'tt0287198',
 'tt0339018',
 'tt0354763',
 'tt0303635',
 'tt0244512',
 'tt0234375',
 'tt0212772',
 'tt0132666',
 'tt0168711',
 'tt0143076',
 'tt11006022',
 'tt0125723',
 'tt0117180',
 'tt0114915',
 'tt0109906',
 'tt0254954',
 'tt0100791',
 'tt0087763',
 'tt0076263',
 'tt0206022',
 'tt0206284',
 'tt2049403',
 'tt13443470',
 'tt29763089',
 'tt29721475',
 'tt29763070',
 'tt28659097',
 'tt3861390',
 'tt1935859',
 'tt1126590',
 'tt5361610',
 'tt1142977',
 'tt1077368',
 'tt1014759',
 'tt0408236',
 'tt6378882',
 'tt0913955',
 'tt0121164',
 'tt0367594',
 'tt0319061',
 'tt0400231',
 'tt0133152',
 'tt0162661',
 'tt0116996',
 'tt2033231',
 'tt0109707',
 'tt0103776',
 'tt31105771',
 'tt0099487',
 'tt0096895',
 'tt0094721',
 'tt0199214',
 'tt0088476',
 'tt0089791',
 'tt0087291',
 'tt0249567',
 'tt0084868',
 'tt0367989',
 'tt5186114',
 'tt0294940',
 'tt0898907',
 'tt5186106',
 'tt5186100',
 'tt5186096',
 'tt5186094',
 'tt0309721',
 'tt2475426',
 'tt5637536',
 'tt3095356',
 'tt1757678',
 'tt1630029',
 'tt6404142',
 'tt15739482',
 'tt0499549',
 'tt0417415',
 'tt0297144',
 'tt0330267',
 'tt0204993',
 'tt0331475',
 'tt15739442',
 'tt0120338',
 'tt0117880',
 'tt0111503',
 'tt25815526',
 'tt15738638',
 'tt0103064',
 'tt0096754',
 'tt1612767',
 'tt0090605',
 'tt0088247',
 'tt0082910',
 'tt0251488',
 'tt10293406',
 'tt2103085',
 'tt0810784',
 'tt0493101',
 'tt0973844',
 'tt0800262',
 'tt0199626',
 'tt0144715',
 'tt0117364',
 'tt0107822',
 'tt0099040',
 'tt0098725',
 'tt0092123',
 'tt0283720',
 'tt0086858',
 'tt0206146',
 'tt0087335',
 'tt0086084',
 'tt0083910',
 'tt2829006',
 'tt6968614',
 'tt4566758',
 'tt5421602',
 'tt1730768',
 'tt2097298',
 'tt11814038',
 'tt2073510',
 'tt0954544',
 'tt0395972',
 'tt0298228',
 'tt0294146',
 'tt0326819',
 'tt0138602',
 'tt0229756',
 'tt6705284',
 'tt3518826',
 'tt9115110',
 'tt19847976',
 'tt13826052',
 'tt1262426',
 'tt1321510',
 'tt7769476',
 'tt6053512',
 'tt8466562',
 'tt7820906',
 'tt9023416',
 'tt3104988',
 'tt3110958',
 'tt3614530',
 'tt4104086',
 'tt3165608',
 'tt1583421',
 'tt6280690',
 'tt4070830',
 'tt1702443',
 'tt2191853',
 'tt1743034',
 'tt1193631',
 'tt3995980',
 'tt8537258',
 'tt1023481',
 'tt10665628',
 'tt0379010',
 'tt0363069',
 'tt10095582',
 'tt6412452',
 'tt0475290',
 'tt2042568',
 'tt1403865',
 'tt1019452',
 'tt0887883',
 'tt0973844',
 'tt5747464',
 'tt0477348',
 'tt0401711',
 'tt0335245',
 'tt8796784',
 'tt0138524',
 'tt0243133',
 'tt0190590',
 'tt0118715',
 'tt0116282',
 'tt0110074',
 'tt0101410',
 'tt0100150',
 'tt0093822',
 'tt0086979',
 'tt6261498',
 'tt6261532',
 'tt6261510',
 'tt7655622',
 'tt0976057',
 'tt3960882',
 'tt11057644',
 'tt2120120',
 'tt2287635',
 'tt8936944',
 'tt0814255',
 'tt21397202',
 'tt21397242',
 'tt1032815',
 'tt0429478',
 'tt0294870',
 'tt0295297',
 'tt0241527',
 'tt0182789',
 'tt0120686',
 'tt0113986',
 'tt0107614',
 'tt0104431',
 'tt0102598',
 'tt0099785',
 'tt0095288',
 'tt0092513',
 'tt5510392',
 'tt6987596',
 'tt31193180',
 'tt13968252',
 'tt9114286',
 'tt1825683',
 'tt3076658',
 'tt5130918',
 'tt2334649',
 'tt2401787',
 'tt1767306',
 'tt1391819',
 'tt10128846',
 'tt2937692',
 'tt1756851',
 'tt0964185',
 'tt0481797',
 'tt3225442',
 'tt0134983',
 'tt0119978',
 'tt0116669',
 'tt0263696',
 'tt0103874',
 'tt0150742',
 'tt0099674',
 'tt0097965',
 'tt0096316',
 'tt0093073',
 'tt0199214',
 'tt0091738',
 'tt0090793',
 'tt0087089',
 'tt0086216',
 'tt0086066',
 'tt0084445',
 'tt0078788',
 'tt0809488',
 'tt0071562',
 'tt0071360',
 'tt0068646',
 'tt0064873',
 'tt0062974',
 'tt0061209',
 'tt0056983',
 'tt0057569',
 'tt0153167',
 'tt0056355',
 'tt0053103',
 'tt10062184',
 'tt22041854',
 'tt14610636',
 'tt18233044',
 'tt9606374',
 'tt18232772',
 'tt22176386',
 'tt5592248',
 'tt6954298',
 'tt4537842',
 'tt7797672',
 'tt8918266',
 'tt2132285',
 'tt8918222',
 'tt1421051',
 'tt8918146',
 'tt0422720',
 'tt1332041',
 'tt7797646',
 'tt7797554',
 'tt0335266',
 'tt3225442',
 'tt7797620',
 'tt0159097',
 'tt0197626',
 'tt7797610',
 'tt0816430',
 'tt7797602',
 'tt20212786',
 'tt14549466',
 'tt15482624',
 'tt3715254',
 'tt2172584',
 'tt3831484',
 'tt1480656',
 'tt1571222',
 'tt0765443',
 'tt14148306',
 'tt0973844',
 'tt21806974',
 'tt0399146',
 'tt0278731',
 'tt1612776',
 'tt0260776',
 'tt0120907',
 'tt0115964',
 'tt0107468',
 'tt0102511',
 'tt0180977',
 'tt0094964',
 'tt0092357',
 'tt0091064',
 'tt0085407',
 'tt0086541',
 'tt0081455',
 'tt0078908',
 'tt0079138',
 'tt8242172',
 'tt0076590',
 'tt0250924',
 'tt0250905',
 'tt0073705',
 'tt0249479',
 'tt0249519',
 'tt0249595',
 'tt0249678',
 'tt0249941',
 'tt0250117',
 'tt0246383',
 'tt0067273',
 'tt0249707',
 'tt0250055',
 'tt0065591',
 'tt0065036',
 'tt0061687',
 'tt0061114',
 'tt4270458',
 'tt1243974',
 'tt1389137',
 'tt1417592',
 'tt1854364',
 'tt0368709',
 'tt0259711',
 'tt0181875',
 'tt0449812',
 'tt0116695',
 'tt0250049',
 'tt0105415',
 'tt7103414',
 'tt0098258',
 'tt7529004',
 'tt21391798',
 'tt16294384',
 'tt6155172',
 'tt2592094',
 'tt1454468',
 'tt12573166',
 'tt0974618',
 'tt0206634',
 'tt0401711',
 'tt0304141',
 'tt0245574',
 'tt0119223',
 'tt0113670',
 'tt0105994',
 'tt0102958',
 'tt0287856',
 'tt0350746',
 'tt0996539',
 'tt0448176',
 'tt6517788',
 'tt4196566',
 'tt10516704',
 'tt8521718',
 'tt9099984',
 'tt4941240',
 'tt3228904',
 'tt1327773',
 'tt1496422',
 'tt0929632',
 'tt0396857',
 'tt8510036',
 'tt8677162',
 'tt3282076',
 'tt1829012',
 'tt0937237',
 'tt0387877',
 'tt0280665',
 'tt0363491',
 'tt0183523',
 'tt0120832',
 'tt0117060',
 'tt0106519',
 'tt0105217',
 'tt0099165',
 'tt0097027',
 'tt0096987',
 'tt0094226',
 'tt26689923',
 'tt0092226',
 'tt4664524',
 'tt6780852',
 'tt0086984',
 'tt0086250',
 'tt0082085',
 'tt0080661',
 'tt0079302',
 'tt0077588',
 'tt0074285',
 'tt0074991',
 'tt0071994',
 'tt0070698',
 'tt0068637',
 'tt0065836',
 'tt0065641',
 'tt0256660',
 'tt0065198',
 'tt0063036',
 'tt0163114',
 'tt0257179',
 'tt0257035',
 'tt0256843',
 'tt0257277',
 'tt0256580',
 'tt0256826',
 'tt7520476',
 'tt26543002',
 'tt1312221',
 'tt1488589',
 'tt7740496',
 'tt7736544',
 'tt1734135',
 'tt5580390',
 'tt2554274',
 'tt2654620',
 'tt3291104',
 'tt4791712',
 'tt0096697',
 'tt1663662',
 'tt0411477',
 'tt0457430',
 'tt0167190',
 'tt0187738',
 'tt0256009',
 'tt0119675',
 'tt0104029',
 'tt0287856',
 'tt0369452',
 'tt0352307',
 'tt13321244',
 'tt4419214',
 'tt19026978',
 'tt11057226',
 'tt12624928',
 'tt7137906',
 'tt1620680',
 'tt7831044',
 'tt5895028',
 'tt7308720',
 'tt4445994',
 'tt1020072',
 'tt1837576',
 'tt2724194',
 'tt3025894',
 'tt1211890',
 'tt1785377',
 'tt1624426',
 'tt1705124',
 'tt1695394',
 'tt1446835',
 'tt1178658',
 'tt0815901',
 'tt27403986',
 'tt1924245',
 'tt3513548',
 'tt7959026',
 'tt6802308',
 'tt3263904',
 'tt2179136',
 'tt1742044',
 'tt1616195',
 'tt1212419',
 'tt1057500',
 'tt1205489',
 'tt0824747',
 'tt0498380',
 'tt0418689',
 'tt0405159',
 'tt0287198',
 'tt0327056',
 'tt0309377',
 'tt0186566',
 'tt14437204',
 'tt0139668',
 'tt0119668',
 'tt0118548',
 'tt0112579',
 'tt0107808',
 'tt0105695',
 'tt0100514',
 'tt0100928',
 'tt0094747',
 'tt0091187',
 'tt0088478',
 'tt0089767',
 'tt0088272',
 'tt0086383',
 'tt0084088',
 'tt0083943',
 'tt0080472',
 'tt0076070',
 'tt0075029',
 'tt0072926',
 'tt0069822',
 'tt0068699',
 'tt0479222',
 'tt0066999',
 'tt0067588',
 'tt3707086',
 'tt3773814',
 'tt10569934',
 'tt5834426',
 'tt6924650',
 'tt8935210',
 'tt1628841',
 'tt3018070',
 'tt2334879',
 'tt2202377',
 'tt1521197',
 'tt1190080',
 'tt0443649',
 'tt0319262',
 'tt0187393',
 'tt0120685',
 'tt0116629',
 'tt0111282',
 'tt0105698',
 'tt0097910',
 'tt0093201',
 'tt0089378',
 'tt0086911',
 'tt31548371',
 'tt0161591',
 'tt1693999',
 'tt31548400',
 'tt5626032',
 'tt30825738',
 'tt8111088',
 'tt12809908',
 'tt10359446',
 'tt11322420',
 'tt6105098',
 'tt6226232',
 'tt5691552',
 'tt3040964',
 'tt2883512',
 'tt2666270',
 'tt0386676',
 'tt2070791',
 'tt0409847',
 'tt0320037',
 'tt1228705',
 'tt0371746',
 'tt0491296',
 'tt13057454',
 'tt0406375',
 'tt0314317',
 'tt0319343',
 'tt0273028',
 'tt0227005',
 'tt0218609',
 'tt1182606',
 'tt1136617',
 'tt9561862',
 'tt10618286',
 'tt5290382',
 'tt2267998',
 'tt6928750',
 'tt3391114',
 'tt1856010',
 'tt11575724',
 'tt1568346',
 'tt1285016',
 'tt2866056',
 'tt0421715',
 'tt0443706',
 'tt1100093',
 'tt6663696',
 'tt0474989',
 'tt11084704',
 'tt10882824',
 'tt0258000',
 'tt6663678',
 'tt0245247',
 'tt0137523',
 'tt0230239',
 'tt0119174',
 'tt8343928',
 'tt6663686',
 'tt0114369',
 'tt7462752',
 'tt0109047',
 'tt0477154',
 'tt6663662',
 'tt0317313',
 'tt7462644',
 'tt6663648',
 'tt6663626',
 'tt7462652',
 'tt0103644',
 'tt6656616',
 'tt0500162',
 'tt6663588',
 'tt6663558',
 'tt6663570',
 'tt6663540',
 'tt6652338',
 'tt6663486',
 'tt6663240',
 'tt6663460',
 'tt6662784',
 'tt5365006',
 'tt6663446',
 'tt6663286',
 'tt2036364',
 'tt6663370',
 'tt6783864',
 'tt6663352',
 'tt6663246',
 'tt6663348',
 'tt10878446',
 'tt6663236',
 'tt6663218',
 'tt6663208',
 'tt6663192',
 'tt6663184',
 'tt6663174',
 'tt6663170',
 'tt6663160',
 ...]